### ISSUE TITLE
Support for Jasmine in-Browser

### ISSUE THREAD

**Issue by leebyron** [leebyron/jasmine-check#2]
jasmine-check currently relies on a node environment and can only be used by jasmine-node. It should support other uses of jasmine such as running in a browser.

**Comment by FrigoEU** [comment]
Hey Lee,

Do you have any idea how you would go about this? I had a good use case for test.check at work today, and bashed something together that works in browsers as well. The things I had to adapt to get it to work:

1. Manually imported testcheck instead of requiring.
2. Instead of exporting the install function, I added jasmine.testcheck.install to the global jasmine object.
3. Commented out the check on version in excel. I'm using jasmine 2.0.0 and there the version is on the jasmine object.
4. Instead of new jasmine.ExpectationResult I used jasmine.buildExpectationResult. Rest of the API seems the same (again, a change that is probably because of jasmine 2.0.0 and not because of node vs browser)

I'm not submitting a PR since it's done so terribly I'm embarrassed, but if there's any interest for this I'd like to hear how you'd do it and maybe put in the effort to make a PR.

Simon
